spring.application.name=catsgram
spring.datasource.url=jdbc:postgresql://localhost/catsgram
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
